import { createClient } from '@supabase/supabase-js'

export const supabase = createClient("https://eqertgbvnnyyqqytvxjt.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZXJ0Z2J2bm55eXFxeXR2eGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTMxNjIsImV4cCI6MjA2MTQ4OTE2Mn0.PPY7wW9U02XmNySowkdxQnh_R5jnvjEouVEBakowpIY")