name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --watchAll=false
      - name: Build
        run: npm run build

  backend:
    name: Backend Lint, Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/api-key-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/api-key-server/package-lock.json
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Lint
        run: npm run lint || true
      - name: Build
        run: npm run build


